import 'package:caterfy/models/order.dart';
import 'package:caterfy/models/order_item.dart';
import 'package:caterfy/models/product.dart';
import 'package:caterfy/models/store.dart';
import 'package:caterfy/models/vendor_order.dart';

final List<Product> dummyProducts = [
  Product(
    id: 'p1',
    storeId: 's1',
    name: 'Classic Beef Burger',
    description: 'Juicy grilled beef patty with lettuce and cheese',
    price: 4.50,
    imageUrl: '',
    subCategoryId: 'c1',
    subCategory: 'Burger',
  ),
  Product(
    id: 'p2',
    storeId: 's1',
    name: 'Chicken Burger',
    description: 'Crispy chicken breast with mayo',
    price: 4.00,
    imageUrl: '',
    subCategoryId: 'c1',
    subCategory: 'Burger',
  ),
  Product(
    id: 'p3',
    storeId: 's1',
    name: 'Cheese Fries',
    description: 'Golden fries topped with melted cheese',
    price: 2.75,
    imageUrl: '',
    subCategoryId: 'c2',
    subCategory: 'Burger',
  ),
  Product(
    id: 'p4',
    storeId: 's1',
    name: 'Cola',
    description: 'Chilled soft drink',
    price: 1.25,
    imageUrl: '',
    subCategoryId: 'c3',
    subCategory: 'Burger',
  ),
  Product(
    id: 'p5',
    storeId: 's1',
    name: 'Chocolate Milkshake',
    description: 'Rich chocolate shake',
    price: 2.50,
    imageUrl: '',
    subCategoryId: 'c3',
    subCategory: 'Burger',
  ),
];

final List<Store> dummyStores = [
  Store(
    id: 'store1',
    vendorId: 'vendor1',
    name: 'FreshMart',
    name_ar: 'فريش مارت',
    category: 'Grocery',
    storeArea: 'Amman',
    logoUrl: '',
    bannerUrl: '',
    tags: ['organic', 'local', 'fresh'],
    latitude: 31.955,
    longitude: 35.945,
  ),
  Store(
    id: 'store2',
    vendorId: 'vendor2',
    name: 'Burger House',
    name_ar: 'برجر هاوس',
    category: 'Fast Food',
    storeArea: 'Irbid',
    logoUrl: '',
    bannerUrl: '',
    tags: ['burgers', 'fries', 'drinks'],
    latitude: 32.556,
    longitude: 35.850,
  ),
  Store(
    id: 'store3',
    vendorId: 'vendor3',
    name: 'TechWorld',
    name_ar: 'تكنولوجي وورلد',
    category: 'Electronics',
    storeArea: 'Zarqa',
    logoUrl: '',
    bannerUrl: '',
    tags: ['gadgets', 'smartphones', 'accessories'],
    latitude: 32.073,
    longitude: 36.086,
  ),
  Store(
    id: 'store4',
    vendorId: 'vendor4',
    name: 'Book Haven',
    name_ar: 'جنة الكتب',
    category: 'Books',
    storeArea: 'Amman',
    logoUrl: '',
    bannerUrl: '',
    tags: ['novels', 'comics', 'education'],
    latitude: 31.945,
    longitude: 35.930,
  ),
  Store(
    id: 'store5',
    vendorId: 'vendor5',
    name: 'StylePoint',
    name_ar: 'ستايل بوينت',
    category: 'Clothing',
    storeArea: 'Aqaba',
    logoUrl: '',
    bannerUrl: '',
    tags: ['fashion', 'men', 'women'],
    latitude: 29.526,
    longitude: 35.007,
  ),
  Store(
    id: 'store6',
    vendorId: 'vendor6',
    name: 'Home Comforts',
    name_ar: 'راحة المنزل',
    category: 'Home & Living',
    storeArea: 'Madaba',
    logoUrl: '',
    bannerUrl: '',
    tags: ['furniture', 'decor', 'kitchen'],
    latitude: 31.716,
    longitude: 35.792,
  ),
  Store(
    id: 'store7',
    vendorId: 'vendor7',
    name: 'Sports Arena',
    name_ar: 'ساحة الرياضة',
    category: 'Sports',
    storeArea: 'Irbid',
    logoUrl: '',
    bannerUrl: '',
    tags: ['equipment', 'wear', 'outdoor'],
    latitude: 32.555,
    longitude: 35.850,
  ),
];

final List<OrderItem> dummyOrderItems = [
  OrderItem(
    id: '${dummyProducts[0].id} 0',
    storeId: dummyProducts[0].storeId,
    name: dummyProducts[0].name,
    imageUrl: dummyProducts[0].imageUrl,
    price: dummyProducts[0].price,
    productId: dummyProducts[0].id,
    note: "THIS IS A RANDOM NOTEEE SAYYING STUPID THINGS :))))",
  ),
  OrderItem(
    id: '${dummyProducts[1].id} 1',
    storeId: dummyProducts[1].storeId,
    name: dummyProducts[1].name,
    imageUrl: dummyProducts[1].imageUrl,
    price: dummyProducts[1].price,
    productId: dummyProducts[1].id,
    note: "THIS IS A RANDOM NOTEEE SAYYING STUPID THINGS :))))",
  ),
  OrderItem(
    id: '${dummyProducts[2].id} 2',
    storeId: dummyProducts[2].storeId,
    name: dummyProducts[2].name,
    imageUrl: dummyProducts[2].imageUrl,
    price: dummyProducts[2].price,
    productId: dummyProducts[2].id,
    note: "THIS IS A RANDOM NOTEEE SAYYING STUPID THINGS :))))",
  ),
  OrderItem(
    id: '${dummyProducts[3].id} 3',
    storeId: dummyProducts[3].storeId,
    name: dummyProducts[3].name,
    imageUrl: dummyProducts[3].imageUrl,
    price: dummyProducts[3].price,
    productId: dummyProducts[3].id,
    note: "THIS IS A RANDOM NOTEEE SAYYING STUPID THINGS :))))",
  ),
  OrderItem(
    id: '${dummyProducts[4].id} 4',
    storeId: dummyProducts[4].storeId,
    name: dummyProducts[4].name,
    imageUrl: dummyProducts[4].imageUrl,
    price: dummyProducts[4].price,
    productId: dummyProducts[4].id,
    note: "THIS IS A RANDOM NOTEEE SAYYING STUPID THINGS :))))",
  ),
];

final List<Order> dummyOrders = [
  Order(
    customerId: "1",
    storeId: "1",
    storeName: "Burger King",
    createdAt: DateTime.now().toString(),
    items: dummyOrderItems,
    deliveryPrice: 1.00,
  ),
  Order(
    customerId: "1",
    storeId: "1",
    storeName: "Burger King",
    createdAt: DateTime.now().toString(),
    items: dummyOrderItems,
    deliveryPrice: 1.00,
  ),
  Order(
    customerId: "1",
    storeId: "1",
    storeName: "Burger King",
    createdAt: DateTime.now().toString(),
    items: dummyOrderItems,
    deliveryPrice: 1.00,
  ),
  Order(
    customerId: "1",
    storeId: "1",
    storeName: "Burger King",
    createdAt: DateTime.now().toString(),
    items: dummyOrderItems,
    deliveryPrice: 1.00,
  ),
  Order(
    customerId: "1",
    storeId: "1",
    storeName: "Burger King",
    createdAt: DateTime.now().toString(),
    items: dummyOrderItems,
    deliveryPrice: 1.00,
  ),
];

List<VendorOrder> dummyVendorOrders = [
  VendorOrder(
    customerId: '1',
    customerName: "David Jones",
    customerEmail: "exampleEmail@gmail.com",
    customerPhone: "+962999999999",
    note: "Extra mayo please habibi <3",
    items: dummyOrderItems,
    createdAt: DateTime.now().toString(),
  ),
  VendorOrder(
    customerId: '1',
    customerName: "David Jones",
    customerEmail: "exampleEmail@gmail.com",
    customerPhone: "+962999999999",
    note: "Extra mayo please habibi <3",
    items: dummyOrderItems,
    createdAt: DateTime.now().toString(),
  ),
  VendorOrder(
    customerId: '1',
    customerName: "David Jones",
    customerEmail: "exampleEmail@gmail.com",
    customerPhone: "+962999999999",
    note: "Extra mayo please habibi <3",
    items: dummyOrderItems,
    createdAt: DateTime.now().toString(),
  ),
  VendorOrder(
    customerId: '1',
    customerName: "David Jones",
    customerEmail: "exampleEmail@gmail.com",
    customerPhone: "+962999999999",
    note: "Extra mayo please habibi <3",
    items: dummyOrderItems,
    createdAt: DateTime.now().toString(),
  ),
  VendorOrder(
    customerId: '1',
    customerName: "David Jones",
    customerEmail: "exampleEmail@gmail.com",
    customerPhone: "+962999999999",
    note: "Extra mayo please habibi <3",
    items: dummyOrderItems,
    createdAt: DateTime.now().toString(),
  ),
];
