import 'package:caterfy/models/product.dart';
import 'package:caterfy/models/store.dart';

final List<Product> dummyProducts = [
  Product(
    id: 'p1',
    storeId: 's1',
    name: 'Classic Beef Burger',
    description: 'Juicy grilled beef patty with lettuce and cheese',
    price: 4.50,
    imageUrl: '',
    subCategoryId: 'c1',
    subCategory: 'Burger',
  ),
  Product(
    id: 'p2',
    storeId: 's1',
    name: 'Chicken Burger',
    description: 'Crispy chicken breast with mayo',
    price: 4.00,
    imageUrl: '',
    subCategoryId: 'c1',
    subCategory: 'Burger',
  ),
  Product(
    id: 'p3',
    storeId: 's1',
    name: 'Cheese Fries',
    description: 'Golden fries topped with melted cheese',
    price: 2.75,
    imageUrl: '',
    subCategoryId: 'c2',
    subCategory: 'Burger',
  ),
  Product(
    id: 'p4',
    storeId: 's1',
    name: 'Cola',
    description: 'Chilled soft drink',
    price: 1.25,
    imageUrl: '',
    subCategoryId: 'c3',
    subCategory: 'Burger',
  ),
  Product(
    id: 'p5',
    storeId: 's1',
    name: 'Chocolate Milkshake',
    description: 'Rich chocolate shake',
    price: 2.50,
    imageUrl: '',
    subCategoryId: 'c3',
    subCategory: 'Burger',
  ),
];

final List<Store> dummyStores = [
  Store(
    id: 'store1',
    vendorId: 'vendor1',
    name: 'FreshMart',
    name_ar: 'فريش مارت',
    category: 'Grocery',
    storeArea: 'Amman',
    logoUrl: '',
    bannerUrl: '',
    tags: ['organic', 'local', 'fresh'],
    latitude: 31.955,
    longitude: 35.945,
  ),
  Store(
    id: 'store2',
    vendorId: 'vendor2',
    name: 'Burger House',
    name_ar: 'برجر هاوس',
    category: 'Fast Food',
    storeArea: 'Irbid',
    logoUrl: '',
    bannerUrl: '',
    tags: ['burgers', 'fries', 'drinks'],
    latitude: 32.556,
    longitude: 35.850,
  ),
  Store(
    id: 'store3',
    vendorId: 'vendor3',
    name: 'TechWorld',
    name_ar: 'تكنولوجي وورلد',
    category: 'Electronics',
    storeArea: 'Zarqa',
    logoUrl: '',
    bannerUrl: '',
    tags: ['gadgets', 'smartphones', 'accessories'],
    latitude: 32.073,
    longitude: 36.086,
  ),
  Store(
    id: 'store4',
    vendorId: 'vendor4',
    name: 'Book Haven',
    name_ar: 'جنة الكتب',
    category: 'Books',
    storeArea: 'Amman',
    logoUrl: '',
    bannerUrl: '',
    tags: ['novels', 'comics', 'education'],
    latitude: 31.945,
    longitude: 35.930,
  ),
  Store(
    id: 'store5',
    vendorId: 'vendor5',
    name: 'StylePoint',
    name_ar: 'ستايل بوينت',
    category: 'Clothing',
    storeArea: 'Aqaba',
    logoUrl: '',
    bannerUrl: '',
    tags: ['fashion', 'men', 'women'],
    latitude: 29.526,
    longitude: 35.007,
  ),
  Store(
    id: 'store6',
    vendorId: 'vendor6',
    name: 'Home Comforts',
    name_ar: 'راحة المنزل',
    category: 'Home & Living',
    storeArea: 'Madaba',
    logoUrl: '',
    bannerUrl: '',
    tags: ['furniture', 'decor', 'kitchen'],
    latitude: 31.716,
    longitude: 35.792,
  ),
  Store(
    id: 'store7',
    vendorId: 'vendor7',
    name: 'Sports Arena',
    name_ar: 'ساحة الرياضة',
    category: 'Sports',
    storeArea: 'Irbid',
    logoUrl: '',
    bannerUrl: '',
    tags: ['equipment', 'wear', 'outdoor'],
    latitude: 32.555,
    longitude: 35.850,
  ),
];
